[package]
name = "better-e7-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
better-e7-adb = { path = "../better-e7-adb" }
better-e7-config = { path = "../better-e7-config" }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time"] }

[lints]
workspace = true

