[workspace]
members = [
    "crates/better-e7-adb",
    "crates/better-e7-app",
    "crates/better-e7-config",
    "crates/better-e7-core",
    "crates/better-e7-runtime",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "UNLICENSED"
repository = "https://github.com/sugurunatsuno/better-e7"
rust-version = "1.88"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
