[package]
name = "better-e7-automation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
better-e7-core = { path = "../better-e7-core" }
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[lints]
workspace = true
